import "./globals.css"
import theme from "@/styles/theme"
import type { Metadata } from "next"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter"
import { Geist, Geist_Mono, Inter } from "next/font/google"
import { ThemeProvider } from "@mui/material"
import QueryProviderWrapper from "../lib/QueryProviderWrapper"
import ModalProvider from "../components/Modal"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const geistInter = Inter({ variable: "--font-geist-mono", subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistInter.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <QueryProviderWrapper>
            <ThemeProvider theme={theme}>
              <ModalProvider>{children}</ModalProvider>
            </ThemeProvider>
          </QueryProviderWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
